Repository Team-Desker/inform-me-desker-ai, pull requests merged in 2025-09, with the labels that each got.

#5 Feat: 방문객 식별 및 채팅 세션 관리 API 구현
  app/api/chat/session/route.js
  app/api/chat/session/route.ts
  chatbot-widget/lib/visitor.ts
  config/constants.js
  package.json
  pnpm-lock.yaml
Labels: ✨ feat, 🚨 codereview : high

#8 Feat: 챗봇 위젯 UI 및 세션 초기화 API 연동
  .gitignore
  app/chat/[sessionID]/page.tsx
  chatbot-widget/App.tsx
  chatbot-widget/components/ChatWindow.tsx
  chatbot-widget/components/ChatbotButton.tsx
  chatbot-widget/index.tsx
  chatbot-widget/test-hompage.html
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/chatbot-widget/loader.js
  public/chatbot-widget/widget.js
  tailwind.config.ts
Labels: 🍎 chore, ✨ feat, 🚨 codereview : high

#15 Design: 챗봇과 대시보드에 사용할 공용 컴포넌트 추가
  app/ui/global.css
  components.json
  components/ai-elements/actions.tsx
  components/ai-elements/branch.tsx
  components/ai-elements/code-block.tsx
  components/ai-elements/conversation.tsx
  components/ai-elements/image.tsx
  components/ai-elements/inline-citation.tsx
  components/ai-elements/loader.tsx
  components/ai-elements/message.tsx
  components/ai-elements/prompt-input.tsx
  components/ai-elements/reasoning.tsx
  components/ai-elements/response.tsx
  components/ai-elements/sources.tsx
  components/ai-elements/suggestion.tsx
  components/ai-elements/task.tsx
  components/ai-elements/tool.tsx
  components/ai-elements/web-preview.tsx
  components/ui/avatar.tsx
  components/ui/badge.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  components/ui/collapsible.tsx
  components/ui/hover-card.tsx
  components/ui/input.tsx
  components/ui/scroll-area.tsx
  components/ui/select.tsx
  components/ui/textarea.tsx
  components/ui/tooltip.tsx
  lib/utils.ts
  package.json
  pnpm-lock.yaml
  tailwind.config.ts
Labels: 🎨 design

#11 Feat: AI SDK 기반 실시간 대화 응답 및 DB 저장 구현
  app/api/chat/[sessionID]/messages/route.ts
  app/api/chat/conversation/route.ts
  config/constants.js
  lib/chat-store.ts
  package.json
  pnpm-lock.yaml
  tailwind.config.ts
Labels: 🍎 chore, ✨ feat

#19 Design: chatroom UI 및 채팅방 상세 메세지 조회 구현
  app/api/dashboard/sessions/[sessionId]/messages/route.ts
  app/api/dashboard/sessions/route.ts
  app/dashboard/[userId]/invoices/page.tsx
  app/dashboard/[userId]/invoices/sessions/[sessionId]/messages/page.tsx
  app/dashboard/[userId]/invoices/sessions/layout.tsx
  app/dashboard/[userId]/invoices/sessions/page.tsx
  app/dashboard/[userId]/layout.tsx
  app/ui/dashboard/side-bar.tsx
  app/ui/dashboard/side-links.tsx
  app/ui/dashboard/side-nav-bar.tsx
  config/constants.js
Labels: 🎨 design

#21 Feat: login api 구현
  app/api/auth/[...nextauth]/route.ts
  auth.edge.ts
  auth.server.ts
  middleware.ts
  package.json
  pnpm-lock.yaml
Labels: 🍎 chore, ✨ feat

#22 Design: login UI 구현 및 auth 인증 연결
  app/(auth)/login/page.tsx
  app/dashboard/[userId]/page.tsx
  app/dashboard/page.tsx
  app/page.tsx
Labels: 🍎 chore, ✨ feat, 🎨 design
